# Generated by Django 6.0.2 on 2026-04-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profilechangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilechangerequest',
            name='new_password',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='profilechangerequest',
            name='request_type',
            field=models.CharField(default='profile', max_length=20),
        ),
        migrations.AlterField(
            model_name='profilechangerequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='profilechangerequest',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profilechangerequest',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
