# Generated by Django 6.0.3 on 2026-04-08 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_default_specializations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoravailability',
            name='slot_duration',
            field=models.IntegerField(default=30, help_text='Slot duration in minutes (15, 30, 45, 60, 90, 120, 150, 180)'),
        ),
    ]
