# Generated by Django 6.0.2 on 2026-04-11 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_doctoravailability_slot_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='core.doctorprofile'),
        ),
        migrations.CreateModel(
            name='DoctorReplacementQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_doctor_name', models.CharField(max_length=100)),
                ('original_date', models.DateField()),
                ('original_time', models.TimeField()),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('assigned', 'Assigned'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_queue', to=settings.AUTH_USER_MODEL)),
                ('specialization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.specialization')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
