# Generated by Django 6.0.2 on 2026-04-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_leave_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('vacation', 'Vacation / Annual Leave'), ('sick', 'Sick Leave'), ('training', 'Training'), ('personal', 'Personal'), ('other', 'Other')], default='vacation', max_length=20),
        ),
    ]
