# Generated by Django 6.0.2 on 2026-04-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_leaverequest_leave_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('vacation', 'Vacation / Annual Leave'), ('sick', 'Sick Leave'), ('training', 'Training'), ('personal', 'Personal'), ('other', 'Other'), ('extension', 'Leave Extension')], default='vacation', max_length=20),
        ),
    ]
