# Generated by Django 6.0.2 on 2026-04-14 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_appointment_fields'),
        ('core', '0012_alter_leaverequest_leave_type'),
    ]

    operations = [
    ]
