# Generated by Django 6.0.2 on 2026-04-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_merge_20260414_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_ref',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
