# Generated by Django 6.0.2 on 2026-04-16 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_reschedule_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('rescheduled', 'Rescheduled'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('delayed', 'Delayed')], default='pending', max_length=15),
        ),
        migrations.CreateModel(
            name='EmergencyCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_phone', models.CharField(blank=True, max_length=15)),
                ('estimated_duration', models.IntegerField(default=30, help_text='Estimated duration in minutes')),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved')], default='active', max_length=10)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergencies', to='core.doctorprofile')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
    ]
