# Generated by Django 6.0.2 on 2026-04-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_doctor_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='unavailable_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
